function  [reliabilitiesPerIterationPso, reliabilitiesPerIterationMcts,...
    numberOfStatesVisitedMcts, energyEfficiencyPerIterationMcts,...
    energyEfficiencyPerIterationPso,numberOfServedUsersPerIterationMcts,...
    numberOfServedUsersPerIterationPso, averageNumberOfEmIters,...
    averageDronePowerMcts, spectralEfficiencyPerIterationMcts]...
    = simulate_mobiquitos(sinr_thresh) 
parameters = struct('a',9.61,...
    'b',0.16,...
    'carrFreq',2e9,...
    'avgLossLOS',1,...
    'avgLossNLOS',20,...
    'totalBandwidth',20e6,...
    'requiredRate',1e6,...
    'spectralEfficiency',2,...
    'noisePower',-140,...
    'sinr_threshold',sinr_thresh,...
    'SNRThresh',35,...
    'linkReliabilityThreshold', 0.95,...
    'dronePower',500,...
    'numberOfDrones',18,...
    'xBoundary',[0 500 1000],...
    'yBoundary',[0 1000],...
    'largeSteps',4,...
    'smallSteps',121,...
    'numberOfUsers',[300 200],...
    'maxIterations',200,... %PSO
    'c1',0.095,...
    'c2',0.1502,...
    'phiMax',0.95,...
    'phiMin',0.92,...
    'phi1Range',[0.8 1.8],...
    'phi2Range',[0.8 1.8],...
    'mctsStep',-100,...
    'maxIterMcts',200);

    
[reliableUsersPerIterationPso,reliabilitiesPerIterationPso,x, energyEfficiencyPerIterationPso, numberOfServedUsersPerIterationPso] = runPso(parameters);
numberOfServedUsersPerIterationPso = reliableUsersPerIterationPso;
% reliabilitiesPerIterationMcts = 0;
% numberOfStatesVisitedMcts = 0;
% energyEfficiencyPerIterationMcts = 0;
% numberOfServedUsersPerIterationMcts = 0;

[reliabilitiesPerIterationMcts, numberOfStatesVisitedMcts, energyEfficiencyPerIterationMcts,...
    numberOfServedUsersPerIterationMcts, averageNumberOfEmIters, averageDronePowerMcts,...
    spectralEfficiencyPerIterationMcts] =runMcts (x, parameters);
% [reliabilitiesPerIterationMcts2, numberOfStatesVisitedMcts2, energyEfficiencyPerIterationMcts2,...
%     numberOfServedUsersPerIterationPso, averageNumberOfEmIters2] =runMcts2 (x, parameters);

