iter = 1;
%%sinrThresholds = -5:22;%%%%%%%%%%
sinr_thresholds = [-2 0 2 5];
results = {};
[reliabilitiesPerIterationPsoTotal_1,reliabilitiesPerIterationMctsTotal_1,...
    numberOfStatesVisitedMctsTotal_1, energyEfficiencyPerIterationMctsTotal_1,...
    energyEfficiencyPerIterationPsoTotal_1,...
    numberOfServedUsersPerIterationMctsTotal_1,...
    numberOfServedUsersPerIterationPsoTotal_1,averageNumberOfEmIters_1,...
    averageDronePowerMcts_1, spectralEfficiencyPerIterationMcts_1]...
    = simulate_mobiquitos(sinr_thresholds(1));



results{1}= {reliabilitiesPerIterationPsoTotal_1,reliabilitiesPerIterationMctsTotal_1,...
    numberOfStatesVisitedMctsTotal_1,energyEfficiencyPerIterationMctsTotal_1,...
    energyEfficiencyPerIterationPsoTotal_1,...
    numberOfServedUsersPerIterationMctsTotal_1,...
    numberOfServedUsersPerIterationPsoTotal_1,averageNumberOfEmIters_1,...
    averageDronePowerMcts_1, spectralEfficiencyPerIterationMcts_1};

[reliabilitiesPerIterationPsoTotal_2,reliabilitiesPerIterationMctsTotal_2,...
    numberOfStatesVisitedMctsTotal_2,energyEfficiencyPerIterationMctsTotal_2,...
    energyEfficiencyPerIterationPsoTotal_2,...
    numberOfServedUsersPerIterationMctsTotal_2,...
    numberOfServedUsersPerIterationPsoTotal_2,averageNumberOfEmIters_2,...
    averageDronePowerMcts_2, spectralEfficiencyPerIterationMcts_2]...
    = simulate_mobiquitos(sinr_thresholds(2));

results{2}= {reliabilitiesPerIterationPsoTotal_2,reliabilitiesPerIterationMctsTotal_2,...
    numberOfStatesVisitedMctsTotal_2,energyEfficiencyPerIterationMctsTotal_2,...
    energyEfficiencyPerIterationPsoTotal_2...
    numberOfServedUsersPerIterationMctsTotal_2,...
    numberOfServedUsersPerIterationPsoTotal_2, averageNumberOfEmIters_2,...
    averageDronePowerMcts_2, spectralEfficiencyPerIterationMcts_2};

[reliabilitiesPerIterationPsoTotal_3,reliabilitiesPerIterationMctsTotal_3,...
    numberOfStatesVisitedMctsTotal_3,energyEfficiencyPerIterationMctsTotal_3,...
    energyEfficiencyPerIterationPsoTotal_3,...
    numberOfServedUsersPerIterationMctsTotal_3,...
    numberOfServedUsersPerIterationPsoTotal_3, averageNumberOfEmIters_3,...
    averageDronePowerMcts_3, spectralEfficiencyPerIterationMcts_3]...
    = simulate_mobiquitos(sinr_thresholds(3));

results{3}= {reliabilitiesPerIterationPsoTotal_3,reliabilitiesPerIterationMctsTotal_3,...
    numberOfStatesVisitedMctsTotal_3,energyEfficiencyPerIterationMctsTotal_3,...
    energyEfficiencyPerIterationPsoTotal_3...
    numberOfServedUsersPerIterationMctsTotal_3,...
    numberOfServedUsersPerIterationPsoTotal_3, averageNumberOfEmIters_3,...
    averageDronePowerMcts_3,spectralEfficiencyPerIterationMcts_3};

[reliabilitiesPerIterationPsoTotal_4,reliabilitiesPerIterationMctsTotal_4,...
    numberOfStatesVisitedMctsTotal_4, energyEfficiencyPerIterationMctsTotal_4,...
    energyEfficiencyPerIterationPsoTotal_4,...
    numberOfServedUsersPerIterationMctsTotal_4,...
    numberOfServedUsersPerIterationPsoTotal_4, averageNumberOfEmIters_4,...
    averageDronePowerMcts_4,spectralEfficiencyPerIterationMcts_4]...
    = simulate_mobiquitos(sinr_thresholds(4));

results{4}= {reliabilitiesPerIterationPsoTotal_4,reliabilitiesPerIterationMctsTotal_4,...
    numberOfStatesVisitedMctsTotal_4, energyEfficiencyPerIterationMctsTotal_4,...
    energyEfficiencyPerIterationPsoTotal_4...
    numberOfServedUsersPerIterationMctsTotal_4,...
    numberOfServedUsersPerIterationPsoTotal_4, averageNumberOfEmIters_4,...
    averageDronePowerMcts_4, spectralEfficiencyPerIterationMcts_4};


while 1
    iter = iter + 1;
    parfor (sinr_threshold_index= 1:length(sinr_thresholds))
        [reliabilitiesPerIterationPso, reliabilitiesPerIterationMcts,...
            numberOfStatesVisitedMcts, energyEfficiencyPerIterationMcts, energyEfficiencyPerIterationPso,...
            numberOfServedUsersPerIterationMcts, numberOfServedUsersPerIterationPso,...
            averageNumberOfEmIters, averageDronePowerMcts, spectralEfficiencyPerIterationMcts]...
            = simulate_mobiquitos(sinr_thresholds(sinr_threshold_index));
        
        results{sinr_threshold_index}{1} = results{sinr_threshold_index}{1}+...
            (reliabilitiesPerIterationPso -results{sinr_threshold_index}{1})./iter;
        
        results{sinr_threshold_index}{2} = results{sinr_threshold_index}{2}+...
            (reliabilitiesPerIterationMcts -results{sinr_threshold_index}{2})./iter;
        
        results{sinr_threshold_index}{3} = results{sinr_threshold_index}{3}+...
            (numberOfStatesVisitedMcts -results{sinr_threshold_index}{3})./iter;
        
        results{sinr_threshold_index}{4} = results{sinr_threshold_index}{4}+...
            (energyEfficiencyPerIterationMcts -results{sinr_threshold_index}{4})./iter;
        
        results{sinr_threshold_index}{5} = results{sinr_threshold_index}{5}+...
            (energyEfficiencyPerIterationPso -results{sinr_threshold_index}{5})./iter;
        
        results{sinr_threshold_index}{6} = results{sinr_threshold_index}{6}+...
            (numberOfServedUsersPerIterationMcts -results{sinr_threshold_index}{6})./iter;
        
        results{sinr_threshold_index}{7} = results{sinr_threshold_index}{7}+...
            (numberOfServedUsersPerIterationPso -results{sinr_threshold_index}{7})./iter;
        
        results{sinr_threshold_index}{8} = results{sinr_threshold_index}{8}+...
            (averageNumberOfEmIters -results{sinr_threshold_index}{8})./iter;
        
        results{sinr_threshold_index}{9} = results{sinr_threshold_index}{9}+...
            (averageDronePowerMcts -results{sinr_threshold_index}{9})./iter;
        
        results{sinr_threshold_index}{10} = results{sinr_threshold_index}{10}+...
            (spectralEfficiencyPerIterationMcts -results{sinr_threshold_index}{10})./iter;
    end
    save('simulation_results','results');
    save('simulation_results_all');
end